[package]
name = "orb-uart"
version = "0.1.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2021"
license.workspace = true

[dependencies]
libc = "0.2"
log.workspace = true
